# Ensemble Learning

## Initial Imports

In [ ]:
import warnings
warnings.filterwarnings('ignore')

In [2]:
import numpy as np
import pandas as pd
from pathlib import Path
from collections import Counter

In [3]:
from sklearn.metrics import balanced_accuracy_score
from sklearn.metrics import confusion_matrix
from imblearn.metrics import classification_report_imbalanced

## Read the CSV and Perform Basic Data Cleaning

In [4]:
# Load the data
file_path = Path('Resources/LoanStats_2019Q1.csv')
df = pd.read_csv(file_path)

# Preview the data
df.head()

,loan_amnt,int_rate,installment,home_ownership,annual_inc,verification_status,issue_d,loan_status,pymnt_plan,dti,...,pct_tl_nvr_dlq,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit,hardship_flag,debt_settlement_flag
0,10500.0,0.1719,375.35,RENT,66000.0,Source Verified,Mar-2019,low_risk,n,27.24,...,85.7,100.0,0.0,0.0,65687.0,38199.0,2000.0,61987.0,N,N
1,25000.0,0.2000,929.09,MORTGAGE,105000.0,Verified,Mar-2019,low_risk,n,20.23,...,91.2,50.0,1.0,0.0,271427.0,60641.0,41200.0,49197.0,N,N
2,20000.0,0.2000,529.88,MORTGAGE,56000.0,Verified,Mar-2019,low_risk,n,24.26,...,66.7,50.0,0.0,0.0,60644.0,45684.0,7500.0,43144.0,N,N
3,10000.0,0.1640,353.55,RENT,92000.0,Verified,Mar-2019,low_risk,n,31.44,...,100.0,50.0,1.0,0.0,99506.0,68784.0,19700.0,76506.0,N,N
4,22000.0,0.1474,520.39,MORTGAGE,52000.0,Not Verified,Mar-2019,low_risk,n,18.76,...,100.0,0.0,0.0,0.0,219750.0,25919.0,27600.0,20000.0,N,N

## Split the Data into Training and Testing

In [5]:
df.describe()

,loan_amnt,int_rate,installment,annual_inc,dti,delinq_2yrs,inq_last_6mths,open_acc,pub_rec,revol_bal,...,num_tl_90g_dpd_24m,num_tl_op_past_12m,pct_tl_nvr_dlq,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit
count,68817.000000,68817.000000,68817.000000,6.881700e+04,68817.000000,68817.000000,68817.000000,68817.000000,68817.000000,68817.000000,...,68817.000000,68817.000000,68817.000000,68817.000000,68817.000000,68817.0,6.881700e+04,6.881700e+04,68817.000000,6.881700e+04
mean,16677.594562,0.127718,480.652863,8.821371e+04,21.778153,0.217766,0.497697,12.587340,0.126030,17604.142828,...,0.052138,2.219423,95.057627,30.626217,0.125972,0.0,2.100332e+05,6.133843e+04,29734.128558,5.572240e+04
std,10277.348590,0.048130,288.062432,1.155800e+05,20.199244,0.718367,0.758122,6.022869,0.336797,21835.880400,...,0.390633,1.897432,8.326426,33.631463,0.336732,0.0,1.928088e+05,5.738798e+04,26795.394232,5.095845e+04
min,1000.000000,0.060000,30.890000,4.000000e+01,0.000000,0.000000,0.000000,2.000000,0.000000,0.000000,...,0.000000,0.000000,20.000000,0.000000,0.000000,0.0,3.600000e+03,2.350000e+02,100.000000,1.270000e+02
25%,9000.000000,0.088100,265.730000,5.000000e+04,13.890000,0.000000,0.000000,8.000000,0.000000,6293.000000,...,0.000000,1.000000,93.000000,0.000000,0.000000,0.0,6.697700e+04,2.650300e+04,11600.000000,2.288000e+04
50%,15000.000000,0.118000,404.560000,7.300000e+04,19.760000,0.000000,0.000000,11.000000,0.000000,12068.000000,...,0.000000,2.000000,100.000000,20.000000,0.000000,0.0,1.467100e+05,4.535700e+04,22100.000000,4.200000e+04
75%,24000.000000,0.155700,648.100000,1.040000e+05,26.660000,0.000000,1.000000,16.000000,0.000000,21735.000000,...,0.000000,3.000000,100.000000,50.000000,0.000000,0.0,3.036400e+05,7.657000e+04,39300.000000,7.249900e+04
max,40000.000000,0.308400,1676.230000,8.797500e+06,999.000000,18.000000,5.000000,72.000000,4.000000,587191.000000,...,18.000000,19.000000,100.000000,100.000000,4.000000,0.0,3.292782e+06,1.295455e+06,509400.000000,1.426964e+06

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 68817 entries, 0 to 68816
Data columns (total 86 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   loan_amnt                   68817 non-null  float64
 1   int_rate                    68817 non-null  float64
 2   installment                 68817 non-null  float64
 3   home_ownership              68817 non-null  object
 4   annual_inc                  68817 non-null  float64
 5   verification_status         68817 non-null  object
 6   issue_d                     68817 non-null  object
 7   loan_status                 68817 non-null  object
 8   pymnt_plan                  68817 non-null  object
 9   dti                         68817 non-null  float64
 10  delinq_2yrs                 68817 non-null  float64
 11  inq_last_6mths              68817 non-null  float64
 12  open_acc                    68817 non-null  float64
 13  pub_rec                     68817 non-null  float64
 14  revol_bal                   68817 non-null  float64
 15  total_acc                   68817 non-null  float64
 16  initial_list_status         68817 non-null  object
 17  out_prncp                   68817 non-null  float64
 18  out_prncp_inv               68817 non-null  float64
 19  total_pymnt                 68817 non-null  float64
 20  total_pymnt_inv             68817 non-null  float64
 21  total_rec_prncp             68817 non-null  float64
 22  total_rec_int               68817 non-null  float64
 23  total_rec_late_fee          68817 non-null  float64
 24  recoveries                  68817 non-null  float64
 25  collection_recovery_fee     68817 non-null  float64
 26  last_pymnt_amnt             68817 non-null  float64
 27  next_pymnt_d                68817 non-null  object
 28  collections_12_mths_ex_med  68817 non-null  float64
 29  policy_code                 68817 non-null  float64
 30  application_type            68817 non-null  object
 31  acc_now_delinq              68817 non-null  float64
 32  tot_coll_amt                68817 non-null  float64
 33  tot_cur_bal                 68817 non-null  float64
 34  open_acc_6m                 68817 non-null  float64
 35  open_act_il                 68817 non-null  float64
 36  open_il_12m                 68817 non-null  float64
 37  open_il_24m                 68817 non-null  float64
 38  mths_since_rcnt_il          68817 non-null  float64
 39  total_bal_il                68817 non-null  float64
 40  il_util                     68817 non-null  float64
 41  open_rv_12m                 68817 non-null  float64
 42  open_rv_24m                 68817 non-null  float64
 43  max_bal_bc                  68817 non-null  float64
 44  all_util                    68817 non-null  float64
 45  total_rev_hi_lim            68817 non-null  float64
 46  inq_fi                      68817 non-null  float64
 47  total_cu_tl                 68817 non-null  float64
 48  inq_last_12m                68817 non-null  float64
 49  acc_open_past_24mths        68817 non-null  float64
 50  avg_cur_bal                 68817 non-null  float64
 51  bc_open_to_buy              68817 non-null  float64
 52  bc_util                     68817 non-null  float64
 53  chargeoff_within_12_mths    68817 non-null  float64
 54  delinq_amnt                 68817 non-null  float64
 55  mo_sin_old_il_acct          68817 non-null  float64
 56  mo_sin_old_rev_tl_op        68817 non-null  float64
 57  mo_sin_rcnt_rev_tl_op       68817 non-null  float64
 58  mo_sin_rcnt_tl              68817 non-null  float64
 59  mort_acc                    68817 non-null  float64
 60  mths_since_recent_bc        68817 non-null  float64
 61  mths_since_recent_inq       68817 non-null  float64
 62  num_accts_ever_120_pd       68817 non-null  float64
 63  num_actv_bc_tl              68817 non-null  float64
 64  num_actv_rev_tl             68817 non-null  float64
 65  num_bc_sats                 68817 non-null  float64
 66  num_bc_tl                   68817 non-null  float64
 67  num_il_tl                   68817 non-null  float64
 68  num_op_rev_tl               68817 non-null  float64
 69  num_rev_accts               68817 non-null  float64
 70  num_rev_tl_bal_gt_0         68817 non-null  float64
 71  num_sats                    68817 non-null  float64
 72  num_tl_120dpd_2m            68817 non-null  float64
 73  num_tl_30dpd                68817 non-null  float64
 74  num_tl_90g_dpd_24m          68817 non-null  float64
 75  num_tl_op_past_12m          68817 non-null  float64
 76  pct_tl_nvr_dlq              68817 non-null  float64
 77  percent_bc_gt_75            68817 non-null  float64
 78  pub_rec_bankruptcies        68817 non-null  float64
 79  tax_liens                   68817 non-null  float64
 80  tot_hi_cred_lim             68817 non-null  float64
 81  total_bal_ex_mort           68817 non-null  float64
 82  total_bc_limit              68817 non-null  float64
 83  total_il_high_credit_limit  68817 non-null  float64
 84  hardship_flag               68817 non-null  object
 85  debt_settlement_flag        68817 non-null  object
dtypes: float64(76), object(10)
memory usage: 45.2+ MB

In [13]:
# Create our features
X = df.drop(columns="loan_status")
X=pd.get_dummies(X,columns=["home_ownership","verification_status",
                            "issue_d","pymnt_plan","initial_list_status",
                            "next_pymnt_d","application_type",
                            "hardship_flag","debt_settlement_flag"
                           ],drop_first=True)
# Create our target
y = df["loan_status"]

In [14]:
# Check the balance of our target values
# YOUR CODE HERE
y.value_counts()

low_risk     68470
high_risk      347
Name: loan_status, dtype: int64

In [15]:
# Split the X and y into X_train, X_test, y_train, y_test
# YOUR CODE HERE
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test= train_test_split(X, 
                                                   y, 
                                                   random_state=1, 
                                                   stratify=y)

## Data Pre-Processing

Scale the training and testing data using the `StandardScaler` from `sklearn`. Remember that when scaling the data, you only scale the features data (`X_train` and `X_testing`).

In [16]:
# Create the StandardScaler instance
# YOUR CODE HERE
from sklearn.preprocessing import StandardScaler
# YOUR CODE HERE
scaler = StandardScaler()

In [17]:
# Fit the Standard Scaler with the training data
# When fitting scaling functions, only train on the training dataset
# YOUR CODE HERE
X_scaler = scaler.fit(X_train)

In [18]:
# Scale the training and testing data
# YOUR CODE HERE
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

## Ensemble Learners

In this section, you will compare two ensemble algorithms to determine which algorithm results in the best performance. You will train a Balanced Random Forest Classifier and an Easy Ensemble classifier . For each algorithm, be sure to complete the folliowing steps:

1. Train the model using the training data. 
2. Calculate the balanced accuracy score from sklearn.metrics.
3. Display the confusion matrix from sklearn.metrics.
4. Generate a classication report using the `imbalanced_classification_report` from imbalanced-learn.
5. For the Balanced Random Forest Classifier only, print the feature importance sorted in descending order (most important feature to least important) along with the feature score

Note: Use a random state of 1 for each algorithm to ensure consistency between tests

### Balanced Random Forest Classifier

In [20]:
# Resample the training data with the BalancedRandomForestClassifier
# YOUR CODE HERE
from imblearn.ensemble import BalancedRandomForestClassifier
from sklearn.datasets import make_classification

model = BalancedRandomForestClassifier(n_estimators=100, random_state=78) 
model = model.fit(X_train_scaled, y_train)

In [23]:
# Calculated the balanced accuracy score
# YOUR CODE HERE
from sklearn.metrics import balanced_accuracy_score
y_pred_BRF = model.predict(X_test_scaled)
balanced_accuracy_score(y_test, y_pred_BRF)

0.8159771323591622

In [22]:
# Display the confusion matrix
# YOUR CODE HERE
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, y_pred_BRF)

array([[   83,     4],
       [14456,  2662]])

In [24]:
# Print the imbalanced classification report
# YOUR CODE HERE
print(classification_report_imbalanced(y_test, y_pred_BRF))

                   pre       rec       spe        f1       geo       iba       sup

  high_risk       0.04      0.72      0.91      0.07      0.81      0.65        87
   low_risk       1.00      0.91      0.72      0.95      0.81      0.67     17118

avg / total       0.99      0.91      0.73      0.95      0.81      0.67     17205

In [25]:
# List the features sorted in descending order by feature importance
# YOUR CODE HERE
importances = rf_model.feature_importances_
sorted(zip(model.feature_importances_, X.columns), reverse=True)

[(0.0923947352854476, 'total_rec_prncp'),
 (0.06440344052758534, 'total_pymnt_inv'),
 (0.06373190617332984, 'total_pymnt'),
 (0.05431687369014751, 'last_pymnt_amnt'),
 (0.0543073345096519, 'total_rec_int'),
 (0.027686987466692722, 'issue_d_Jan-2019'),
 (0.02609874526954735, 'int_rate'),
 (0.020351603147581183, 'installment'),
 (0.01941891202456689, 'out_prncp_inv'),
 (0.018392908245194333, 'mo_sin_old_il_acct'),
 (0.018001267949225092, 'dti'),
 (0.01666699567184789, 'annual_inc'),
 (0.015596738471699982, 'il_util'),
 (0.015078425125715852, 'bc_util'),
 (0.01479942827879941, 'revol_bal'),
 (0.014446671918464974, 'mths_since_recent_inq'),
 (0.01438407288540484, 'mo_sin_old_rev_tl_op'),
 (0.01438366614526355, 'out_prncp'),
 (0.014103357063922854, 'tot_cur_bal'),
 (0.013885032555783907, 'max_bal_bc'),
 (0.013875232679928462, 'tot_hi_cred_lim'),
 (0.013624332773858662, 'avg_cur_bal'),
 (0.013222400327715073, 'total_rev_hi_lim'),
 (0.012677527225226854, 'bc_open_to_buy'),
 (0.01180401882900855, 'issue_d_Mar-2019'),
 (0.011775578668869574, 'total_bc_limit'),
 (0.011769076426069346, 'total_bal_il'),
 (0.01173123885633965, 'mths_since_rcnt_il'),
 (0.011533428604408119, 'total_bal_ex_mort'),
 (0.011380416068613237, 'all_util'),
 (0.010974717782699074, 'total_il_high_credit_limit'),
 (0.010906074879656594, 'num_rev_accts'),
 (0.010624559115758707, 'total_acc'),
 (0.010368318719969495, 'mths_since_recent_bc'),
 (0.010194653276858775, 'num_bc_tl'),
 (0.010077383411137232, 'num_il_tl'),
 (0.01004941930569905, 'loan_amnt'),
 (0.01002442234326067, 'mo_sin_rcnt_rev_tl_op'),
 (0.010010997031916864, 'open_acc'),
 (0.009643179460592085, 'num_bc_sats'),
 (0.009234318617983212, 'num_op_rev_tl'),
 (0.00905593016131315, 'mo_sin_rcnt_tl'),
 (0.008906405331732174, 'inq_last_12m'),
 (0.00817246679522884, 'open_il_24m'),
 (0.008170290549657276, 'num_actv_rev_tl'),
 (0.008042069311398696, 'total_cu_tl'),
 (0.007985168410742574, 'num_sats'),
 (0.007852767265802415, 'open_act_il'),
 (0.007639567481484251, 'acc_open_past_24mths'),
 (0.007374274074831373, 'num_actv_bc_tl'),
 (0.007329738267372425, 'num_rev_tl_bal_gt_0'),
 (0.00661448203318194, 'pct_tl_nvr_dlq'),
 (0.006379755071540535, 'percent_bc_gt_75'),
 (0.006246565561903209, 'mort_acc'),
 (0.006140148428608858, 'total_rec_late_fee'),
 (0.005903459798492958, 'num_tl_op_past_12m'),
 (0.005723650598789439, 'inq_last_6mths'),
 (0.005366130070053515, 'inq_fi'),
 (0.005360190784759372, 'open_rv_24m'),
 (0.004998396704999371, 'next_pymnt_d_May-2019'),
 (0.004590031670862302, 'delinq_2yrs'),
 (0.004471540781935444, 'open_il_12m'),
 (0.0040960467902561425, 'open_acc_6m'),
 (0.00407090977366138, 'open_rv_12m'),
 (0.0029775952537887188, 'verification_status_Verified'),
 (0.0029437863294874693, 'num_accts_ever_120_pd'),
 (0.0028664966146225938, 'home_ownership_OWN'),
 (0.0023624679347272015, 'tot_coll_amt'),
 (0.0018573447689793137, 'verification_status_Source Verified'),
 (0.0016627365463979889, 'pub_rec_bankruptcies'),
 (0.001467640661598957, 'home_ownership_RENT'),
 (0.0014388651502600007, 'home_ownership_MORTGAGE'),
 (0.001142754834615683, 'application_type_Joint App'),
 (0.0011037913327908522, 'pub_rec'),
 (0.0008466255711725881, 'initial_list_status_w'),
 (0.000593325307547482, 'num_tl_90g_dpd_24m'),
 (0.00022296149926701977, 'collections_12_mths_ex_med'),
 (7.322566469423641e-05, 'chargeoff_within_12_mths'),
 (0.0, 'tax_liens'),
 (0.0, 'recoveries'),
 (0.0, 'policy_code'),
 (0.0, 'num_tl_30dpd'),
 (0.0, 'num_tl_120dpd_2m'),
 (0.0, 'delinq_amnt'),
 (0.0, 'collection_recovery_fee'),
 (0.0, 'acc_now_delinq')]

### Easy Ensemble Classifier

In [26]:
# Train the Classifier
# YOUR CODE HERE
from imblearn.ensemble import EasyEnsembleClassifier


model = EasyEnsembleClassifier(n_estimators=100, random_state=78) 
model = model.fit(X_train_scaled, y_train)

In [27]:
# Calculated the balanced accuracy score
# YOUR CODE HERE
y_pred_EEC = model.predict(X_test_scaled)
balanced_accuracy_score(y_test, y_pred_EEC)

0.9275304075967624

In [28]:
# Display the confusion matrix
# YOUR CODE HERE
confusion_matrix(y_test, y_pred_EEC)

array([[   79,     8],
       [  907, 16211]])

In [29]:
# Print the imbalanced classification report
# YOUR CODE HERE
print(classification_report_imbalanced(y_test, y_pred_BRF))

                   pre       rec       spe        f1       geo       iba       sup

  high_risk       0.04      0.72      0.91      0.07      0.81      0.65        87
   low_risk       1.00      0.91      0.72      0.95      0.81      0.67     17118

avg / total       0.99      0.91      0.73      0.95      0.81      0.67     17205

### Final Questions

1. Which model had the best balanced accuracy score?

    YOUR ANSWER HERE.

2. Which model had the best recall score?

    YOUR ANSWER HERE.

3. Which model had the best geometric mean score?

    YOUR ANSWER HERE.

4. What are the top three features?

    YOUR ANSWER HERE.

In [ ]:
1 Easy Ensemble Classifier has higher score
2 These two models have same recall score
3 These two models have same geo score
4 The top three features are 'total_rec_prncp','total_pymnt_inv' and 'total_pymt'